default:
  username: spring
  password: boot

marklogic:
  host: localhost
  port: 8005
  username: admin
  password: admin

spring:
  thymeleaf:
    # Allow Thymeleaf templates to be reloaded at dev time
    cache: false

server:
  tomcat:
    access_log_enabled: true
    basedir: target/tomcat